version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  detailed:
    format: "%(asctime)s [%(levelname)8s] %(name)s:%(lineno)d - %(funcName)s() - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  
  json:
    format: "%(asctime)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    
  performance:
    format: "%(asctime)s [PERF] %(name)s - %(message)s - Duration: %(duration).3fs"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  info_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  training_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/training.log
    maxBytes: 52428800  # 50MB
    backupCount: 10
    encoding: utf8
  
  performance_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: performance
    filename: logs/performance.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf8

loggers:
  irst_library:
    level: DEBUG
    handlers: [console, debug_file, info_file, error_file]
    propagate: False
  
  irst_library.training:
    level: INFO
    handlers: [console, training_file]
    propagate: False
  
  irst_library.models:
    level: INFO
    handlers: [console, debug_file]
    propagate: False
  
  irst_library.datasets:
    level: INFO
    handlers: [console, debug_file]
    propagate: False
  
  irst_library.performance:
    level: INFO
    handlers: [performance_file]
    propagate: False
  
  # Third-party libraries
  torch:
    level: WARNING
    handlers: [console]
    propagate: False
  
  matplotlib:
    level: WARNING
    handlers: [console]
    propagate: False
  
  PIL:
    level: WARNING
    handlers: [console]
    propagate: False

root:
  level: INFO
  handlers: [console, info_file, error_file]
