apiVersion: v1
kind: ServiceMonitor
metadata:
  name: irst-library-metrics
  labels:
    app: irst-library
spec:
  selector:
    matchLabels:
      app: irst-library
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: irst-library-alerts
  labels:
    app: irst-library
spec:
  groups:
  - name: irst-library.rules
    rules:
    - alert: IRSTHighErrorRate
      expr: rate(irst_api_errors_total[5m]) > 0.1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High error rate in IRST API"
        description: "Error rate is {{ $value }} errors per second"
    
    - alert: IRSTHighLatency
      expr: histogram_quantile(0.95, rate(irst_api_duration_seconds_bucket[5m])) > 1.0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High latency in IRST API"
        description: "95th percentile latency is {{ $value }} seconds"
    
    - alert: IRSTLowThroughput
      expr: rate(irst_api_requests_total[5m]) < 10
      for: 10m
      labels:
        severity: info
      annotations:
        summary: "Low throughput in IRST API"
        description: "Request rate is {{ $value }} requests per second"
    
    - alert: IRSTHighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"irst-library-.*"} / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High memory usage in IRST container"
        description: "Memory usage is {{ $value | humanizePercentage }} of limit"
    
    - alert: IRSTHighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"irst-library-.*"}[5m]) / container_spec_cpu_quota * 100 > 80
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage in IRST container"
        description: "CPU usage is {{ $value }}%"
